//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LappiaSPWeb.Root.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LappiaRoot {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LappiaRoot() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LappiaSPWeb.Root.Resources.LappiaRoot", typeof(LappiaRoot).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagemap.
        /// </summary>
        internal static string bcPagemap {
            get {
                return ResourceManager.GetString("bcPagemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Detail.
        /// </summary>
        internal static string bcProjectDetail {
            get {
                return ResourceManager.GetString("bcProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Listing.
        /// </summary>
        internal static string bcProjectListing {
            get {
                return ResourceManager.GetString("bcProjectListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inprogress.
        /// </summary>
        internal static string Inprogress {
            get {
                return ResourceManager.GetString("Inprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string lblAttachments {
            get {
                return ResourceManager.GetString("lblAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding.
        /// </summary>
        internal static string lblFinding {
            get {
                return ResourceManager.GetString("lblFinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string lblLogo {
            get {
                return ResourceManager.GetString("lblLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        internal static string lblMoreInfo {
            get {
                return ResourceManager.GetString("lblMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Partners.
        /// </summary>
        internal static string lblOurPartners {
            get {
                return ResourceManager.GetString("lblOurPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Finding.
        /// </summary>
        internal static string lblSourceFinding {
            get {
                return ResourceManager.GetString("lblSourceFinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string lblSupervisor {
            get {
                return ResourceManager.GetString("lblSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string lblTarget {
            get {
                return ResourceManager.GetString("lblTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Table.
        /// </summary>
        internal static string lblTimeTable {
            get {
                return ResourceManager.GetString("lblTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string lblWebsite {
            get {
                return ResourceManager.GetString("lblWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string pcContact {
            get {
                return ResourceManager.GetString("pcContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        internal static string pcContentType {
            get {
                return ResourceManager.GetString("pcContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string pcDesc {
            get {
                return ResourceManager.GetString("pcDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÄÄRIN.
        /// </summary>
        internal static string pcFalse {
            get {
                return ResourceManager.GetString("pcFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nimi.
        /// </summary>
        internal static string pcName {
            get {
                return ResourceManager.GetString("pcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sivun asettelun.
        /// </summary>
        internal static string pcPageLayout {
            get {
                return ResourceManager.GetString("pcPageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Content Type.
        /// </summary>
        internal static string pcRelatedContentType {
            get {
                return ResourceManager.GetString("pcRelatedContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string pcReview {
            get {
                return ResourceManager.GetString("pcReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string pcTitle {
            get {
                return ResourceManager.GetString("pcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project status.
        /// </summary>
        internal static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string projListingHeading {
            get {
                return ResourceManager.GetString("projListingHeading", resourceCulture);
            }
        }
    }
}
